version: '3'
services:
   nodejs-jwt:
      image: nodejs-jwt
      build:
         context: .
         dockerfile: dockerfile
      restart: unless-stopped
      #stdin_open: true
      #tty: true
      #command: sh
      environment:
        - MONGO_URI=${MONGO_URI}
        - TOKEN_KEY=${TOKEN_KEY}
        - API_PORT=${API_PORT}
        - DEBUG=true
      ports:
         - ${API_PORT}:${API_PORT}
      networks:
         - demo
networks:
   demo:
      external: true   