version: '3'
services:
   demo:
      build:
         context: .
         dockerfile: dockerfile
      restart: unless-stopped
      stdin_open: true
      tty: true
      ports:
         - "3001:3001"
      networks:
         - demo
networks:
   demo:
      external: true   